myapp/urls.py
from django.urls import path
from myapp.views import index,detail,PostCreate,like

app_name = 'myapp'


urlpatterns = [
    path('',index,name = 'index'),
    path('detail/<int:pk>/',detail,name='detail'),
    path('create/',PostCreate.as_view(),name='create'),
    path('ajax/like/',like,name='like'),
      

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('accounts/', include('registration.backends.default.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserTimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Post(UserTimeStamp):
	title = models.CharField(max_length = 100)
	description = models.TextField()
	image = models.ImageField(upload_to = '')
	likes=models.IntegerField(default=0)

	def __str__(self):
		return self.title


class Comment(UserTimeStamp):
	post = models.ForeignKey(Post, on_delete = models.CASCADE)
	comment = models.TextField()

myapp/forms.py
from django import forms
from myapp.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

myapp/views.py
from django.shortcuts import render,redirect
from myapp.models import Post,Comment
from myapp.forms import CommentForm
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
# Create your views here.
def index(request):
	# process the request here
	p = Post.objects.all()
	context = {'posts':p}
	return render(request,'index.html',context)

'''def detail(request,pk):
	d = Post.objects.get(pk = pk)
	context = {'post':d}
	return render(request,'detail.html',context)'''
@login_required
def detail(request,pk):
    d = Post.objects.get(pk = pk)
    comments = Comment.objects.filter(post = d)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            comment = form.cleaned_data['comment']
            c = Comment(post = d,comment = comment,user = request.user)
            c.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            context = {'post':d,'form':form,'comments':comments}
            return render(request, 'detail.html', context)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()
    context = {'post':d,'form':form,'comments':comments}
    return render(request, 'detail.html', context)

class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','description','image']
    success_url='/'


    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)
def like(request):
    if request.is_ajax():
        i=request.GET.get('i')
        p=Post.objects.get(pk=i)
        p.likes+=1
        p.save()
        data={'i':p.likes}
        return JsonResponse(data)

myapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>MYAPP</title>
	<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:create' %}">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>&nbsp; 
    </form>
    {% if user.is_authenticated %}
     {{request.user}}<a class="btn btn-outline-danger" href="{% url 'auth_logout' %}">Logout</a>&nbsp; 
    {% else %}
    <a class="btn btn-outline-primary" href="{% url 'registration_register' %}">Register</a>&nbsp; 
    <a class="btn btn-outline-primary" href="{% url 'auth_login' %}">Login</a>&nbsp; 
    {% endif %}
    
  </div>
</nav>
<div class="container">
 {% block content %}
 
 {% endblock %}

</div>
<footer class="footer">
      <div class="container">
        <span class="text-muted">@2020</span>
      </div>
    </footer>
</body>
</html>

myapp/templates/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="col-6">
{{post.title}}<br>
{{post.description}}<br>
<img src="{{post.image.url}}" height="300" width="300"><br>
created at :{{post.created_at}} by {{post.user}}<br>
updated at :{{post.updated_at}}
<br>
<div>

<span id="likes">{{post.likes}}</span>likes<button class="btn btn-info" onclick="onClick()">Like</button>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
	function onClick(){
		$.ajax({
			url:"{% url 'myapp:like' %}",
			data:{'i':{{post.id}}},
			dataType:'json',
			success:function(data){
				document.getElementById('likes').innerHTML=data.i
			}
		})


		
	}
</script>
<br>
</div>
<div class="col-6">

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
</form>
</div>
</div>
<br><br>
<h5>Comments</h5>
{% if comments %}
{% for i in comments %}
{{i.comment}}<br>
at {{i.created_at}} by {{i.user}}<br>
<hr>
{% endfor %}
{% endif %}


{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row">

{% for i in posts %}
	<div class="col-6">

<a href="{% url 'myapp:detail' i.pk %}"><b>{{i.title}}</b></a><br>

<img src="{{i.image.url}}" height="300" width="300"><br>
<br><br>

{{i.created_by}}<br>
</div>

{% endfor %}
<br>
</div>
{% endblock %}